#ifndef AMGRAPH_H
#define AMGRAPH_H
#include <QString>
#define ENDLESS 1844674407

class AMGraph
{
public:
    const static int n = 13;//顶点数量
    QString vexs[n+1] = {"\0","乌鲁木齐","银川","北京","哈尔滨","郑州","上海","拉萨","成都","武汉","南宁","海口","香港","广州"};;//顶点表
    int arcs[n+1][n+1] = {
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,ENDLESS,1662,2624,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,3836},
        {ENDLESS,1662,ENDLESS,ENDLESS,ENDLESS,ENDLESS,2047,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,2624,ENDLESS,ENDLESS,1056,690,1040,ENDLESS,ENDLESS,1052,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,ENDLESS,ENDLESS,1056,ENDLESS,ENDLESS,1854,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,ENDLESS,ENDLESS,690,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,467,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,ENDLESS,2047,1040,1854,ENDLESS,ENDLESS,ENDLESS,1670,ENDLESS,ENDLESS,ENDLESS,1265,1150},
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,1300,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS},
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,1670,1300,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,1223},
        {ENDLESS,ENDLESS,ENDLESS,1052,ENDLESS,467,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,873},
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,728},
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,482},
        {ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,1265,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,ENDLESS,119},
        {ENDLESS,3836,ENDLESS,ENDLESS,ENDLESS,ENDLESS,1150,ENDLESS,1223,873,728,482,119,ENDLESS}

    };//关系表
    AMGraph();
    bool DFS(int v);

};

#endif // AMGRAPH_H
